// Mock data extracted from your Google Sheet
const MOCK_TASKS = [
  {
    "id": "1",
    "task": "Create Global selling Doc ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-02",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "2",
    "task": "Reachout VAAREE email+ phone for onboarding",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-02",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "3",
    "task": "Create weekly Report",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "All clients",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-02",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "4",
    "task": "Thematic Categories DPA Launch",
    "assignedTo": "Harsh",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-02",
    "completedOn": "Feb 6, 2026 | 11:42 AM",
    "remarks": "Astrology, Celestial and Products > \u20b9598 Launched"
  },
  {
    "id": "5",
    "task": "Swingsaga Delightchat flow update as per Juhi",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-02",
    "remarks": ""
  },
  {
    "id": "6",
    "task": "Swingsaga Location content generation",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-02",
    "remarks": ""
  },
  {
    "id": "7",
    "task": "Review delightchat tickets to find optimisation opportunites",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-02",
    "remarks": ""
  },
  {
    "id": "8",
    "task": "Go through the super leads and paid tickets to improve the flow",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-02",
    "remarks": ""
  },
  {
    "id": "9",
    "task": "Swingsaga product category update",
    "assignedTo": "Sidd",
    "status": "In progress",
    "client": "Swingsaga",
    "assignedOn": "2026-02-01",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "10",
    "task": "Vasavi International shipping partner exploration",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": "Shiprocket X (Best for Global Scale and US Markets)\n    \u25e6 Cost Efficiency: Offers a unique \"deadweight\" billing model for specific US shipping lanes. This is critical for apparel (which is often voluminous but light), potentially improving unit economics by 30-50% compared to standard volumetric billing.\n    \u25e6 Network Reach: Aggregates services from global carriers like DHL and FedEx, providing coverage to over 220 countries with express delivery options.\n    \u25e6 Agency Support: Provides a mature \"Partner Program\" with a dedicated Key Account Manager to handle escalations and a unified dashboard for managing client shipping volumes.\n\niThink Logistics (Best for Risk Aversion and Reducing Returns)\n    \u25e6 Superior Support: Differentiates itself with a \"support-first\" architecture, boasting a 4-hour resolution time compared to the industry average of 8-24 hours.\n    \u25e6 Return Reduction: Utilizes an AI-driven system to verify addresses and confirm buyer availability, significantly lowering Return-to-Origin (RTO) rates to 12% (compared to the Shiprocket average of 18%).\n    \u25e6 Branding Control: Offers a robust white-labeling feature that allows agencies to completely customize tracking pages with the client's brand, removing the logistics provider's branding entirely.\n"
  },
  {
    "id": "11",
    "task": "Add multiple swing rotating video (9390) in the last msg of the DC flow",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-02",
    "remarks": ""
  },
  {
    "id": "12",
    "task": "Create a dedicated FAQ page for swingsaga",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "13",
    "task": "Technical SEO - Merchant Schema, Organisation Schema (Global)",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-02",
    "remarks": ""
  },
  {
    "id": "14",
    "task": "Technical SEO - Review schema, Shipping details, Return policy",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "15",
    "task": "Relist AV amazon Sku + Ad that in new campaign",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Anything Vegan",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "16",
    "task": "Setup Kaching Bundles - Inkup",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "17",
    "task": "Local SEO schema for swingsaga",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "18",
    "task": "Create discount 20% OFF on Handpainted Planters",
    "assignedTo": "Danish",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "19",
    "task": "Publish Inkup Seo Content ",
    "assignedTo": "Danish",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "20",
    "task": "Collection page named as marketplace for confetti",
    "assignedTo": "Danish",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": "Connect with Harsh for more info"
  },
  {
    "id": "21",
    "task": "Shipping and duty update mimamsaa",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Mimamsaa",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": "Ref to the Mimamsaa grp msg timed at around 4:57PM"
  },
  {
    "id": "22",
    "task": "Send onboarding emails to Mimamsaa and Banter Kitchen",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "All clients",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "23",
    "task": "Review Growth update (monthly form)",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "24",
    "task": "Backlink Agency Call 1pm",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "25",
    "task": "Fix Review schema error in swingsaga",
    "assignedTo": "Armaan",
    "status": "In progress",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "26",
    "task": "Mimamsa Access Call",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Mimamsaa",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "27",
    "task": "Send Location Based content",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "28",
    "task": "Send emails to dashboard client for monthly performance update.",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "29",
    "task": "Add location Content for Swingsaga",
    "assignedTo": "Danish",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": "Yet to recive the location document form team."
  },
  {
    "id": "30",
    "task": "Handpainted Planters ads",
    "assignedTo": "Harsh",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "31",
    "task": "Weekly Report",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-01",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": "Pending on others' updates"
  },
  {
    "id": "32",
    "task": "Weekly Report",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "2026-02-01",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": "Pending on others' updates"
  },
  {
    "id": "33",
    "task": "Weekly Report",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Anything Vegan",
    "assignedOn": "2026-02-01",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-05",
    "remarks": ""
  },
  {
    "id": "34",
    "task": "Weekly Report",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-01",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "35",
    "task": "Weekly Report",
    "assignedTo": "Rishav",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-01",
    "deadline": "2026-02-03",
    "completedOn": "Feb 5, 2026 | 5:58 PM",
    "remarks": ""
  },
  {
    "id": "36",
    "task": "Vasavi Delhivery product and order sync issue",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "Feb 6, 2026 | 12:53 PM",
    "remarks": ""
  },
  {
    "id": "37",
    "task": "Generate blogs for Swingsaga",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": "Swingsaga Blogs (Feb 5, 2026)"
  },
  {
    "id": "38",
    "task": "LLMs.txt for all brands",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "All clients",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "39",
    "task": "Generate blogs for Vasavi",
    "assignedTo": "Sidd",
    "status": "Not started",
    "client": "Vasavi",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "40",
    "task": "Generate blogs for AV",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Anything Vegan",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-05",
    "remarks": "Anything Vegan Blogs (Feb 5, 2026)"
  },
  {
    "id": "41",
    "task": "Add whatsapp chat popup on craft delights",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": "Added into the theme but we need to improve the whatsapp flow before making it live"
  },
  {
    "id": "42",
    "task": "SEO Title (Meta and OG) for all products must be optimised for Buy intent (swingsaga)",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "43",
    "task": "Create new Safe-T claim for amazon refund ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "44",
    "task": "Generate blogs for craft delights",
    "assignedTo": "Sidd",
    "status": "Not started",
    "client": "Craft Delights",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "45",
    "task": "Generate blogs for Inkup",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-05",
    "remarks": "Inkup Blogs (Feb 5, 2026)"
  },
  {
    "id": "46",
    "task": "Generate Vasavi collection (drop) content",
    "assignedTo": "Sidd",
    "status": "Not started",
    "client": "Vasavi",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "47",
    "task": "Swingsaga - figureout the alternative for watermark on image",
    "assignedTo": "Faisal",
    "status": "In progress",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "48",
    "task": "Find US leads (10)",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "49",
    "task": "Create PPT (5) ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "50",
    "task": "Connect with Myntra POC ( Trial run + Cod disable)",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "51",
    "task": "Analyse GSC data and generate blogs based on Keywords",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "Feb 6, 2026 | 4:43 PM",
    "remarks": ""
  },
  {
    "id": "52",
    "task": "Big Atom setup",
    "assignedTo": "Harsh",
    "status": "In progress",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "53",
    "task": "Offers strategy",
    "assignedTo": "Harsh",
    "status": "In progress",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": "Discussion is done, specifics on pricing awaited"
  },
  {
    "id": "54",
    "task": "Craft Amazon 2 product listing ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "55",
    "task": "Create Shiment and connect RO - Blinkit ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "56",
    "task": "Connect with Shristty regarding gloabl selling doc ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "57",
    "task": "Submit again application of Susprise ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "58",
    "task": "Submit pet product - Swing saga",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "59",
    "task": "Brand Research and Audit",
    "assignedTo": "Harsh",
    "status": "Not started",
    "client": "Mimamsaa",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "60",
    "task": "Weekly Report",
    "assignedTo": "Rishav",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "Feb 5, 2026 | 5:22 PM",
    "remarks": ""
  },
  {
    "id": "61",
    "task": "Test the swingsaga updated DC flow",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "62",
    "task": "LLMS.txt Add",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "63",
    "task": "Publish Swingsaga DC updated flow",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "64",
    "task": "Update Craft DC Flow as per Manish",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "65",
    "task": "Change the track order msg for Craft",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "66",
    "task": "Change the brand name in all DC flow msgs - CD",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "67",
    "task": "Enable COD verification, order confirmation and fulfillment status msgs",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "68",
    "task": "Connect Instagram, FB - DM and comments as support channel in CD",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "69",
    "task": "Enable automation flow for IG, FB DM in DC for CD",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "2026-02-03",
    "remarks": ""
  },
  {
    "id": "70",
    "task": "first 2 images look big on desktop, need to be same size as the other 3 images",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "NDNY",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "71",
    "task": "New Delhi - New York, is moving too fast. We need to slow it down and not on top of each other. Plus reduce the white space in this from top and bottom to half",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "NDNY",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "72",
    "task": "Meeting with Shirishty",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "73",
    "task": "Thumbnail and timestamps",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "74",
    "task": "Last image/sketch of the store needs to be changed. If you can please give me size and link to where needs to be updated, I can add some and reviw",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "NDNY",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "75",
    "task": "first 2 images look big on desktop, need to be same size as the other 3 images",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "NDNY",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "76",
    "task": "bottom footer looks great except the image quality is blurred",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "NDNY",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-03",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "77",
    "task": "Find USA leads (10)",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "78",
    "task": "Create PPT (5) ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "79",
    "task": "Feb Plan",
    "assignedTo": "Harsh",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "80",
    "task": "Verify all the access from Banter Kitchen",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Banter Kitchen",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "81",
    "task": "Google Ads Brand Search Launch",
    "assignedTo": "Harsh",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": "Account funding awaited. Campaign Launched"
  },
  {
    "id": "82",
    "task": "Launch Shivansh's video on Profile Visits",
    "assignedTo": "Rishav",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 5:22 PM",
    "remarks": ""
  },
  {
    "id": "83",
    "task": "Add all SOPs in GG OS Pro sheet",
    "assignedTo": "Sidd",
    "status": "Not started",
    "client": "Go Growth",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "84",
    "task": "Explore all the features of GoKwik AB test - Inkup",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 4:18 PM",
    "remarks": ""
  },
  {
    "id": "85",
    "task": "List MARIO + Space theme on Amazon - Craft",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "86",
    "task": "Go through call notes (inkup)",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "87",
    "task": "Purchase popup like swingsaga on Inkup",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "88",
    "task": "xx number of people viewing this product Inkup - product page",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": " q",
    "remarks": ""
  },
  {
    "id": "89",
    "task": "Competitor Spy platform to find out best selling products",
    "assignedTo": "Sidd",
    "status": "In progress",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "90",
    "task": "Pull up the data for B2G1 sales %",
    "assignedTo": "Sidd",
    "status": "Not started",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "91",
    "task": "Meeting with Inkup",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "Feb 6, 2026 | 4:44 PM",
    "remarks": "Assigned tasks related to website changes to Armaan and 1 task to Danish (shoppable video x products)"
  },
  {
    "id": "92",
    "task": "Google Referral Custom Conversion",
    "assignedTo": "Harsh",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "Feb 6, 2026 | 11:43 AM",
    "remarks": ""
  },
  {
    "id": "93",
    "task": "Couples Tattoos Ads on DPA",
    "assignedTo": "Harsh",
    "status": "In progress",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "94",
    "task": "Freckles as Gifting angle Ads for Valentines day",
    "assignedTo": "Harsh",
    "status": "In progress",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-05",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "95",
    "task": "Inkup Local Business Schema",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-05",
    "completedOn": "Feb 6, 2026 | 6:51 PM",
    "remarks": "\u200b"
  },
  {
    "id": "96",
    "task": "KwikPass research and comparison",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "97",
    "task": "Shiprocket engage360 research and comparison",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "98",
    "task": "Research about Nitro for Inkup",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "99",
    "task": "Add more alt images",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "100",
    "task": "Website usability seo improvements",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "101",
    "task": "Inkup <> KwikPass Demo call",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 6, 2026 | 4:46 PM",
    "remarks": ""
  },
  {
    "id": "102",
    "task": "Test Vasavi Automation flow on DC",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 6, 2026 | 4:46 PM",
    "remarks": ""
  },
  {
    "id": "103",
    "task": "Onboard Confetti on Interakt",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-07",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "104",
    "task": "Create email for pop up shop",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "105",
    "task": "Explore Amazon International Selling programme",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Banter Kitchen",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-09",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "106",
    "task": "Vasavi order sync with delhivery issue",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "Feb 5, 2026 | 3:21 PM",
    "deadline": "2026-02-05",
    "completedOn": "Feb 6, 2026 | 4:46 PM",
    "remarks": ""
  },
  {
    "id": "107",
    "task": "Myntra catalouge live",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "108",
    "task": "llms.txt add ",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "2026-02-04",
    "remarks": ""
  },
  {
    "id": "109",
    "task": "Discount setup on GoKwik - Inkup",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-06",
    "completedOn": "Feb 6, 2026 | 4:46 PM",
    "remarks": ""
  },
  {
    "id": "110",
    "task": "Youtube ads set up - Craft ",
    "assignedTo": "Piyush",
    "status": "In progress",
    "client": "Craft Delights",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "111",
    "task": "eBay Listing ",
    "assignedTo": "Piyush",
    "status": "In progress",
    "client": "Swingsaga",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": "Waiting for pricing from clinet side"
  },
  {
    "id": "112",
    "task": "Start Susprise listing ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "113",
    "task": "Finalize myntra listing",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "Feb 6, 2026 | 10:21 AM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "114",
    "task": "Create Ticket for Return order",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "Feb 5, 2026 | 7:05 PM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "115",
    "task": "Connect with Myntra poc for live inventory",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "Feb 6, 2026 | 10:23 AM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "116",
    "task": "Find USA leads  ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "Feb 6, 2026 | 10:23 AM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "117",
    "task": "Create ppt  ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "Feb 6, 2026 | 10:23 AM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "118",
    "task": "Google ad conversion label configuration on Craft",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Craft Delights",
    "assignedOn": "Feb 6, 2026 | 11:31 AM",
    "deadline": "2026-02-06",
    "completedOn": "Feb 6, 2026 | 6:51 PM",
    "remarks": ""
  },
  {
    "id": "119",
    "task": "SEO Score improvements",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-03",
    "deadline": "2026-02-07",
    "completedOn": "Feb 6, 2026 | 12:54 PM",
    "remarks": ""
  },
  {
    "id": "120",
    "task": "Microsoft Clarity Installation",
    "assignedTo": "Faisal",
    "status": "Need Help",
    "client": "Mimamsaa",
    "assignedOn": "Feb 6, 2026 | 12:56 PM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": "They're having trouble finding the confirmation email."
  },
  {
    "id": "121",
    "task": "SEO improvements",
    "assignedTo": "Faisal",
    "status": "In progress",
    "client": "Banter Kitchen",
    "assignedOn": "Feb 6, 2026 | 12:57 PM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "122",
    "task": "Announcement bar text update",
    "assignedTo": "Danish",
    "status": "Completed",
    "client": "Mimamsaa",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-04",
    "completedOn": "",
    "remarks": "\"We've absorbed all US customs duties so you pay nothing extra (Shipping still applies).\""
  },
  {
    "id": "123",
    "task": "Shipping error fix",
    "assignedTo": "Faisal",
    "status": "Not started",
    "client": "Swingsaga",
    "assignedOn": "Feb 6, 2026 | 1:01 PM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "124",
    "task": "Increase the number of customers in CRO popup on Inkup (add 15-18 names for rotation)",
    "assignedTo": "Armaan",
    "status": "Not started",
    "client": "Inkup",
    "assignedOn": "Feb 6, 2026 | 3:53 PM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "125",
    "task": "upload meadia for ramadan bundle & marketplace page ",
    "assignedTo": "Danish",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "2026-02-05",
    "deadline": "",
    "completedOn": "Feb 6, 2026 | 9:33 AM",
    "remarks": ""
  },
  {
    "id": "126",
    "task": "Change the color of \"number of people viewing this product\" to red",
    "assignedTo": "Armaan",
    "status": "Not started",
    "client": "Inkup",
    "assignedOn": "Feb 6, 2026 | 3:55 PM",
    "deadline": "2026-02-06",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "127",
    "task": "Find email of existing leads",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 6:32 PM",
    "remarks": ""
  },
  {
    "id": "128",
    "task": "Create PPT (5) ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 2:19 PM",
    "remarks": ""
  },
  {
    "id": "129",
    "task": "Find US leads",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Go Growth",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 2:19 PM",
    "remarks": ""
  },
  {
    "id": "130",
    "task": "\"Notify Me\" Feature for Out of Stock products",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-07",
    "completedOn": "Feb 6, 2026 | 1:47 PM",
    "remarks": ""
  },
  {
    "id": "131",
    "task": "Review Swingsaga chats with latest flow",
    "assignedTo": "Sidd",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 4:32 PM",
    "remarks": ""
  },
  {
    "id": "132",
    "task": "New Landing Page(s) Copy",
    "assignedTo": "Rishav",
    "status": "Completed",
    "client": "Anything Vegan",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-07",
    "completedOn": "Feb 6, 2026 | 4:23 PM",
    "remarks": ""
  },
  {
    "id": "133",
    "task": "Ads sheet similar to SEO Sheet made by Faisal",
    "assignedTo": "Rishav",
    "status": "Completed",
    "client": "All clients",
    "assignedOn": "Feb 5, 2026 | 5:04 PM",
    "deadline": "2026-02-07",
    "completedOn": "Feb 6, 2026 | 4:42 PM",
    "remarks": ""
  },
  {
    "id": "134",
    "task": "Audit and study all ad accounts",
    "assignedTo": "Rishav",
    "status": "Completed",
    "client": "All clients",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 5:22 PM",
    "remarks": ""
  },
  {
    "id": "135",
    "task": "Swingsaga Find guest posting blogs for review and comparison article",
    "assignedTo": "Faisal",
    "status": "In progress",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "136",
    "task": "Listicles for Swingsaga in different categories",
    "assignedTo": "Rishav",
    "status": "Not started",
    "client": "Swingsaga",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "137",
    "task": "Inkup Cro",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-05",
    "deadline": "",
    "completedOn": "2026-02-05",
    "remarks": ""
  },
  {
    "id": "138",
    "task": "Google Tracking Issues",
    "assignedTo": "Faisal, Sidd",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 5:06 PM",
    "remarks": ""
  },
  {
    "id": "139",
    "task": "Social Media Add Website + CRO",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 2:04 PM",
    "remarks": ""
  },
  {
    "id": "140",
    "task": "Inkup AI Report",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 2:08 PM",
    "remarks": ""
  },
  {
    "id": "141",
    "task": "Start Amazon Global selling onboarding for ( USA + Aus )",
    "assignedTo": "Piyush",
    "status": "In progress",
    "client": "Swingsaga",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": "Pending from Shristy side"
  },
  {
    "id": "142",
    "task": "Flipart transaction issue - shared by Shristy ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Swingsaga",
    "assignedOn": "Feb 5, 2026 | 2:21 PM",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 7:02 PM",
    "remarks": ""
  },
  {
    "id": "143",
    "task": "Re-add the templates",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "Feb 5, 2026 | 4:39 PM",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 4:45 PM",
    "remarks": ""
  },
  {
    "id": "144",
    "task": "Conversion IDs and Labels + Goals GoQuick",
    "assignedTo": "Faisal",
    "status": "Completed",
    "client": "Inkup",
    "assignedOn": "Feb 5, 2026 | 4:17 PM",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 4:57 PM",
    "remarks": ""
  },
  {
    "id": "145",
    "task": "Create markets for US, UK, Australia, UAE, etc.",
    "assignedTo": "Armaan",
    "status": "Completed",
    "client": "Vasavi",
    "assignedOn": "2026-02-05",
    "deadline": "2026-02-09",
    "completedOn": "Feb 6, 2026 | 1:02 PM",
    "remarks": ""
  },
  {
    "id": "146",
    "task": "New Arrivals Email + Whatsapp",
    "assignedTo": "Harsh",
    "status": "Not started",
    "client": "Inkup",
    "assignedOn": "2026-02-04",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "147",
    "task": "Back in stock Email + Whatsapp",
    "assignedTo": "Harsh",
    "status": "Not started",
    "client": "Inkup",
    "assignedOn": "2026-02-02",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "148",
    "task": "Home and Collection Page Content",
    "assignedTo": "Faisal",
    "status": "Not started",
    "client": "Banter Kitchen",
    "assignedOn": "Feb 6, 2026 | 12:57 PM",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": ""
  },
  {
    "id": "149",
    "task": "Convert Image into 1:1 ",
    "assignedTo": "Piyush",
    "status": "Completed",
    "client": "Confetti",
    "assignedOn": "Feb 5, 2026 | 6:32 PM",
    "deadline": "2026-02-05",
    "completedOn": "Feb 5, 2026 | 7:02 PM",
    "remarks": ""
  },
  {
    "id": "150",
    "task": "Location Page Content",
    "assignedTo": "Faisal",
    "status": "Not started",
    "client": "Banter Kitchen",
    "assignedOn": "Feb 6, 2026 | 12:57 PM",
    "deadline": "2026-02-07",
    "completedOn": "",
    "remarks": ""
  }
];

// Mock Resources Data
const MOCK_RESOURCES = [
    {
        id: '1',
        name: 'SEO Best Practices Guide',
        description: 'Comprehensive guide on SEO optimization strategies and techniques for e-commerce websites',
        link: 'https://example.com/seo-guide',
        tag: 'SEO',
        remarks: 'Must read for all team members',
        createdBy: 'Harsh',
        createdOn: '2026-01-15'
    },
    {
        id: '2',
        name: 'Google Ads Dashboard',
        description: 'Main dashboard for managing all client ad campaigns',
        link: 'https://ads.google.com/dashboard',
        tag: 'Ads',
        remarks: '',
        createdBy: 'Piyush',
        createdOn: '2026-01-20'
    },
    {
        id: '3',
        name: 'N8N Automation Workflows',
        description: 'Collection of automation workflows for task management and reporting',
        link: 'https://n8n.io/workflows',
        tag: 'N8N',
        remarks: 'Check weekly for updates',
        createdBy: 'Sidd',
        createdOn: '2026-02-01'
    },
    {
        id: '4',
        name: 'Brand Design System',
        description: 'Complete brand guidelines, color palettes, and design assets',
        link: 'https://figma.com/brand-system',
        tag: 'Design',
        remarks: '',
        createdBy: 'Faisal',
        createdOn: '2026-01-25'
    },
    {
        id: '5',
        name: 'Website Analytics Template',
        description: 'Google Analytics dashboard template for client reporting',
        link: 'https://analytics.google.com/template',
        tag: 'Analytics',
        remarks: 'Use this for monthly reports',
        createdBy: 'Danish',
        createdOn: '2026-02-05'
    }
];
