// Mock Data for GoGrowth OS Pro - Used when database is not available

const mockTasks = [
  {
    _id: '1',
    title: 'Build responsive dashboard',
    description: 'Create a mobile-friendly dashboard design',
    priority: 'High',
    status: 'In progress',
    assignedTo: 'John Doe',
    client: 'TechCorp',
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    tags: ['design', 'ui', 'mobile'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    title: 'Integrate payment gateway',
    description: 'Add Stripe payment integration',
    priority: 'High',
    status: 'Pending',
    assignedTo: 'Jane Smith',
    client: 'StartupXYZ',
    deadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['backend', 'payments', 'integration'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    title: 'Fix bug in authentication',
    description: 'JWT token expiration not working correctly',
    priority: 'Critical',
    status: 'In progress',
    assignedTo: 'Mike Johnson',
    client: 'TechCorp',
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['bugs', 'security', 'backend'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints',
    priority: 'Medium',
    status: 'Completed',
    assignedTo: 'Sarah Wilson',
    client: 'Internal',
    deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['documentation', 'api'],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    _id: '5',
    title: 'Setup CI/CD pipeline',
    description: 'Create automated deployment with GitHub Actions',
    priority: 'High',
    status: 'Pending',
    assignedTo: 'Alex Chen',
    client: 'Internal',
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['devops', 'automation', 'backend'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '6',
    title: 'Design new logo',
    description: 'Create a modern logo for the brand refresh',
    priority: 'Medium',
    status: 'In progress',
    assignedTo: 'Emily Brown',
    client: 'ClientABC',
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['design', 'branding', 'creative'],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '7',
    title: 'Code review - PR #234',
    description: 'Review new features in pull request 234',
    priority: 'Low',
    status: 'Pending',
    assignedTo: 'John Doe',
    client: 'Internal',
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['code-review', 'quality'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '8',
    title: 'Update database schema',
    description: 'Add new fields for enhanced tracking',
    priority: 'Medium',
    status: 'In progress',
    assignedTo: 'Mike Johnson',
    client: 'TechCorp',
    deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['database', 'backend', 'schema'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '9',
    title: 'Optimize image compression',
    description: 'Reduce image file sizes for faster loading',
    priority: 'Low',
    status: 'Completed',
    assignedTo: 'Jane Smith',
    client: 'StartupXYZ',
    deadline: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['performance', 'frontend', 'optimization'],
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    _id: '10',
    title: 'Client meeting preparation',
    description: 'Prepare presentation for quarterly business review',
    priority: 'Medium',
    status: 'Pending',
    assignedTo: 'Sarah Wilson',
    client: 'ClientABC',
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['meetings', 'presentation', 'client'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

const mockResources = [
  {
    _id: '1',
    title: 'React Documentation',
    description: 'Official React docs for learning and reference',
    category: 'Learning',
    type: 'Documentation',
    url: 'https://react.dev',
    status: 'Active',
    tags: ['react', 'frontend', 'javascript'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    title: 'MongoDB Atlas',
    description: 'Cloud database service for MongoDB',
    category: 'Tools',
    type: 'Service',
    url: 'https://www.mongodb.com/cloud/atlas',
    status: 'Active',
    tags: ['database', 'mongodb', 'backend'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    title: 'Tailwind CSS Guide',
    description: 'Complete guide to utility-first CSS framework',
    category: 'Learning',
    type: 'Tutorial',
    url: 'https://tailwindcss.com/docs',
    status: 'Active',
    tags: ['tailwind', 'css', 'styling'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    title: 'Express.js API Best Practices',
    description: 'Guide to building secure and scalable APIs',
    category: 'Learning',
    type: 'Article',
    url: 'https://expressjs.com/en/advanced/best-practice-performance.html',
    status: 'Active',
    tags: ['express', 'backend', 'best-practices'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '5',
    title: 'Figma Design Tool',
    description: 'Collaborative design and prototyping platform',
    category: 'Tools',
    type: 'Software',
    url: 'https://www.figma.com',
    status: 'Active',
    tags: ['design', 'ui', 'collaboration'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '6',
    title: 'GitHub Actions CI/CD',
    description: 'Automate testing, building, and deployment',
    category: 'Tools',
    type: 'Service',
    url: 'https://github.com/features/actions',
    status: 'Active',
    tags: ['devops', 'automation', 'cicd'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '7',
    title: 'JavaScript Async/Await Guide',
    description: 'Understanding asynchronous programming patterns',
    category: 'Learning',
    type: 'Tutorial',
    url: 'https://javascript.info/async-await',
    status: 'Active',
    tags: ['javascript', 'async', 'learning'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '8',
    title: 'Google Sheets API',
    description: 'Integrate Google Sheets with your applications',
    category: 'Tools',
    type: 'API',
    url: 'https://developers.google.com/sheets/api',
    status: 'Active',
    tags: ['google', 'sheets', 'api', 'integration'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  mockTasks,
  mockResources,
};
